GET http://localhost:8080/api/image/5ed656cab58ee332e48eaf14

###
GET http://localhost:8080/api/image/product/5ed75a533684fe7140ac77f7

###

POST http://localhost:8080/api/products
Content-Type: multipart/form-data; boundary=FormDataRow

--FormDataRow
Content-Disposition: form-data; name="productBody"
Content-Type: application/json

{
    "price": "199",
    "name": "Wheat Fields",
    "category": "Sea",
    "description": "An atmospheric glade with trees, the sun is shining in through the tree tops",
    "inventory": "10",
    "cartAmount": "0"
}

--FormDataRow
Content-Disposition: form-data; name="image"; filename="jelly.jpg"
Content-Type: image/jpeg

< ./jelly.jpg

--FormDataRow--

### Content-Type kan också vara image/png beroende på bildens extension

### Tänk på följande:
### ALLA boundary's måste BÖRJA med --
### SISTA boundary'n måste AVSLUTAS med --