// Orders


//GET all
GET http://localhost:8080/api/orders

###

//GET order by userId
GET http://localhost:8080/api/orders/5ecbf1b742932536cc47965f

###


//Post order
POST http://localhost:8080/api/orders
Content-Type: application/json

{
    "products": ["Skål"],
    "shipment": "DHL",
    "totalPrice": 999,
    "deliveryAddress": {
        "address": "the street",
        "zipcode": 1,
        "city": "city"
    }
}

###