// Products

// Get all products
GET http://localhost:8080/api/products/

###

// Post new product
POST http://localhost:8080/api/products
Content-Type: multipart/form-data; boundary=FormDataRow

--FormDataRow
Content-Disposition: form-data; name="productBody"
Content-Type: application/json

{
    "price": "279",
    "name": "Mountains at Dusk",
    "category": "Mountains",
    "description": "A snow-covered mountain surrounded by pine trees",
    "inventory": "5",
    "cartAmount": "0"
}

--FormDataRow
Content-Disposition: form-data; name="image"; filename="mountain-forest.jpg"
Content-Type: image/jpeg

< ./mountain-forest.jpg

--FormDataRow--

### Content-Type kan också vara image/png beroende på bildens extension

### Tänk på följande:
### ALLA boundary's måste BÖRJA med --
### SISTA boundary'n måste AVSLUTAS med --

###

// Update a product
PUT http://localhost:8080/api/products/5ed7903574c28384bc088f01
Content-Type: application/json

{
    "inventory": "18",
    "_id": "5ed7903574c28384bc088f01"
}

###

// Get all products in category
GET http://localhost:8080/api/products/category/blue

###

// Get one specific product
GET http://localhost:8080/api/products/product/5ec7d055dfbbcd4930b76b3d

###

// Update stock 
PUT http://localhost:8080/api/products/
Content-Type: application/json

[
{
    "_id": "5ed7a92d25f95d92f2ae1750",
    "price": 279,
    "name": "Iceberg",
    "category": "Water",
    "description": "Aerial view of an iceberg floating in the turquoise sea of Sermersooq, Greenland",
    "inventory": 10,
    "cartAmount": 1,
    "imageId": "5ed7a92c25f95d92f2ae174e"
},
{
    "_id": "5ed7ad3625f95d92f2ae1759",
    "price": 229,
    "name": "Autumn Waterfall",
    "category": "Water",
    "description": "A lively yet calm waterfall during autumn in Portland, USA",
    "inventory": 10,
    "cartAmount": 1,
    "imageId": "5ed7ad3625f95d92f2ae1757"
}
]

