// Products

// Get all products
GET http://localhost:8080/api/products/

###

// Post new product
POST http://localhost:8080/api/products/
Content-Type: application/json

{
    "price": "225",
     "name": "Trees in a forest",
     "category": "Forest",
     "description": "An atmospheric glade with trees, the sun is shining in through the tree tops",
     "inventory": "8"
}

###

// Update a product
PUT http://localhost:8080/api/products/5ec7cdd8dfbbcd4930b76b3c
Content-Type: application/json

{
    "price": "199",
    "name": "Clodus in sky",
    "category": "Sky",
    "description": "White, fluffy clouds in the sky on a blue summers sky",
    "inventory": "10"
}

###

// Get all products in category
GET http://localhost:8080/api/products/category/blue

###

// Get one specific product
GET http://localhost:8080/api/products/product/5ec7d055dfbbcd4930b76b3d

###

// Update stock 
PUT http://localhost:8080/api/products/
Content-Type: application/json

[
{
    "_id": "5ec7cdd8dfbbcd4930b76b3c",
    "quantity": 2
},
{
    "_id": "5ec7d87e2e3c8232a853dc36",
    "quantity": 1
}
]

