// Products

// Get all products
GET http://localhost:8080/api/products/

###

// Post new product
POST http://localhost:8080/api/products/
Content-Type: application/json

{
    "price": "225",
     "name": "Katt",
     "category": "Forest",
     "description": "An atmospheric glade with trees, the sun is shining in through the tree tops",
     "inventory": "8",
     "cartAmount": 0
}

###

// Update a product
PUT http://localhost:8080/api/products/5ecfd69aabe87203ec813aa7
Content-Type: application/json

{
    "inventory": "10"
}

###

// Get all products in category
GET http://localhost:8080/api/products/category/blue

###

// Get one specific product
GET http://localhost:8080/api/products/product/5ec7d055dfbbcd4930b76b3d

###

// Update stock 
PUT http://localhost:8080/api/products/
Content-Type: application/json

[
{
    "_id": "5ec7cdd8dfbbcd4930b76b3c",
    "quantity": 2
},
{
    "_id": "5ec7d87e2e3c8232a853dc36",
    "quantity": 1
}
]

