// Sessions

// Login
POST http://localhost:8080/sessions/login
Content-Type: application/json

{
    "email": "email",
    "password": "admin"
}

###

###

//LOGOUT
DELETE http://localhost:8080/sessions/logout

###

//CHECK SESSION
GET http://localhost:8080/sessions/checkLoginSession