// users

GET http://localhost:8080/api/users/

###

POST http://localhost:8080/api/users/
Content-Type: application/json

{
    "name": "Emelie345",
    "lastname": "lastname",
    "email": "email1",
    "password": "admin",
    "role": "true",
    "deliveryAddress": {
        "address": "street",
        "zipcode": 1,
        "city": "city"
    }
}

###

