// users

//Get all

GET http://localhost:8080/api/users/

###

//Get one

GET http://localhost:8080/api/users/5ecba68a7d085f4d744cb891

###

POST http://localhost:8080/api/users/register
Content-Type: application/json

{
    "name": "Emelie",
    "lastname": "Lastname",
    "email": "emai5",
    "password": "admin",
    "role": "Admin",
    "deliveryAddress": {
        "address": "street",
        "zipcode": 1,
        "city": "city"
    }
}

###

